version: "3.3"

services:
  p2p_wazobia_db:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysql_volume:/etc
    ports:
      - "3306:3306"
    expose:
      - 3306
volumes:
  mysql_volume:
